### ISSUE TITLE
Practical example?

### ISSUE THREAD

**Issue by trusktr** [jarofghosts/dom-delegation-stream#5]
Can you provide a more practical example showing how this becomes more useful over, say, jQuery event handling?

**Comment by RangerMauve** [comment]
Since streams are very composable, you could have a more declarative, or functional, approach to defining your application. [Here's](https://github.com/RangerMauve/distribu-click/blob/master/client.js) an example app I made whose logic is entirely stream-based.

However there's been some progress, and rather than "streams" it might make sense to take a look at libraries that deal with Observables such as [bacon](https://baconjs.github.io/), [RxJS](https://github.com/Reactive-Extensions/RxJS#why-rxjs) or my personal favorite: [flyd](https://github.com/paldepind/flyd). The advantage of using Node streams is that there's a bunch of modules existing in the ecosystem that work on Node streams, however the various Observable libraries are also starting to become popular, and are usually more lightweight since they don't bring all the extra stuff Node streams bring for dealing with slow connections.

**Comment by jarofghosts** [comment]
Echoing what @RangerMauve said, we started using Node-style streams + browserify a long time ago to architect our app in a "reactive" and/or more functional way.

The wealth of existing streaming modules is what keeps us, though we understand that we are _kind_ of abusing them as a means of flow control (`objectMode` and/or Streams1 **everywhere**). Another great benefit is that as you write more modules, they feed into the streaming module ecosystem and benefit a much larger audience of people.

I would definitely argue that modeling your app as a series of pipelines of data is by far the best way that I have found to manage complexity, though. I wrote a (now somewhat outdated) [blog post](https://jarofghosts.github.io/front-end-streams) on the matter, complete with examples. That said, as was mentioned, there are other options out there if you are willing to lose a little bit of reusability.

**Comment by RangerMauve** [comment]
Also: Here's a shameless plugin for [a library I made](https://github.com/RangerMauve/implexus) which lets you wire up streams together using a graph. :D What you end up doing in code when you use streams can basically be done decoratively with this.

**Comment by trusktr** [comment]
Thanks guys! That gives me some good perspective. :) :+1:
